### ISSUE TITLE
Be made part of Atom Core.

### ISSUE THREAD

**Issue by k2b6s9j** [AtomLinterPlus/linter-plus#1]
An idea occurred to me on my way home today. Maybe the linter core should be made part of Atom core, much like AutoComplete. But I'd love to hear ideas from everyone involved.

/cc @AsaAyers @hd-deman @iam4x @iam4x @steelbrain @kevinsawicki @dmnd @maxbrunsfeld
/cc Anyone else who has an opinion on/would be influenced by this.

Here's my thought process. Knowing where issues in your code/project exists is essential to coding, therefore it should be an essential part of the editor itself. This allows us to continue making linter providers/independent linters and optimize for their specific environments. This will also encourage a larger community if the core linter is part of the core.

Again, I could be totally out of line in this but, given the recent drama I thought it might be possible that the community and use cases of AtomLinter have grown too large for it's own independent organization and community and should be made a core part of the Atom community, especially given how many Atom users are dependent on AtomLinter and it's linters.

**Comment by steelbrain** [comment]
:+1:

**Comment by k2b6s9j** [comment]
The OmniSharp guys are largely effected by this as well.
/cc @david-driscoll @nosami @ctolkien @Mpdreamz @sgwill

**Comment by k2b6s9j** [comment]
And the guy from atom-lint
/cc @yujinakayama

**Comment by david-driscoll** [comment]
My biggest issue with linter today, is that it has to save a file to disk.  This looks to be resolved with the new api in linter-plus.

Getting this added to core would be great for us, because it's one less thing we needed to depend on for the user to have installed.

/cc atom-typescript as well @basarat

**Comment by k2b6s9j** [comment]
@david-driscoll Aren't AtomLinter and atom-yeoman the only things you automatically install on first run, since AutoComplete was made core?

**Comment by david-driscoll** [comment]
That's correct, would mean we would just need atom-yeoman.

**Comment by k2b6s9j** [comment]
@david-driscoll That would be really awesome.

**Comment by k2b6s9j** [comment]
The guys at atom-haskell might want in on this conversation too.
/cc @lierdakil @chaika2013

**Comment by AsaAyers** [comment]
I intend to continue as planned and release a new version of linter that it's backwards compatible with all of the new features. this allows for a smooth upgrade process for everyone. 

in your rush to get this incorporated into core please keep in mind that this repository is born out of impatience

**Comment by k2b6s9j** [comment]
@AsaAyers I realize that, just seemed like a good place to start a conversation with the wider community.

**Comment by lierdakil** [comment]
That's interesting conversation, and I will keep an eye on this, but we don't depend on AtomLinter. @mdgriffith, who works on [linter-hlint][1], would be directly affected though.

[1]: https://github.com/AtomLinter/linter-hlint

**Comment by k2b6s9j** [comment]
@lierdakil Would your IDE package benefit from a linter package made core?

**Comment by lierdakil** [comment]
@k2b6s9j, I'm... not entirely convinced it would. We have custom system for displaying errors/warnings/lints, which IMO is better-suited for our case, since we don't do on-line check. If it makes to core, though, I might find a way to leverage that, but frankly, I don't want to think too hard about it in this early stages of discussion.

I like the idea in general, though, since that would, simply put, offer more functionality out of the box.

That said, after reading [wiki page on service-provider API][1], it seems a little rough around the edges. That could use some polish before inclusion into core, IMO. (I could provide some examples of what immediately came to mind, but I think this is not the place to discuss API necessarily)

[1]: https://github.com/AtomLinterPlus/linter-plus/wiki/Linter-API

**Comment by k2b6s9j** [comment]
@lierdakil In one of the providers I wrote not too long ago, it doesn't use the in-line check but uses linter-plus's project error window to show error for the project. You might wanna check out [k2b6s9j/linter-flint](https://github.com/k2b6s9j/linter-flint).

![screen shot 2015-06-07 at 12 10 30 pm](https://cloud.githubusercontent.com/assets/594124/8069817/68acaa4a-0eba-11e5-8e83-557451956fea.png)

**Comment by k2b6s9j** [comment]
Also, @lierdakil could you open issues on either AtomLinter/linter-plus or on this repo for the API ideas you have in mind?

**Comment by lierdakil** [comment]
What I meant was, linter's project error window doesn't appear well-suited for long, multi-line error messages, that Haskell likes to spew out. Sorry about the poor choice of words.

**Comment by k2b6s9j** [comment]
Don't worry about it. So if the error window were optimized for longer messages, and this API were made part of the core, you would utilize it?

**Comment by lierdakil** [comment]
I'm reluctant to commit to anything yet, but yes, possibly. I tend to prefer using what core has to offer if it doesn't hurt functionality, since it allows for more unified look-and-feel across the board.

**Comment by ctolkien** [comment]
We've also (in omnisharp) implemented our own error window (as have the typescript guys). So it definitely feels like we're each solving the same problem several times over.

**Comment by k2b6s9j** [comment]
Please continue this conversation at AtomLinter/linter-plus#47
